services:
  userservice:
    image: registry.starboardsocial.nl/userservice:prod
    container_name: 'StarboardSocial-UserService'
    restart: unless-stopped
    depends_on:
      - userservice_db
    networks:
      - starboardsocial_net
      - user_starboardsocial_net
    environment:
      Rabbit__UserName: ${RABBIT_USERNAME}
      Rabbit__Password: ${RABBIT_PASSWORD}
      Rabbit__VirtualHost: /
      Rabbit__HostName: rabbitmq
      Rabbit__Port: 5672
      ConnectionStrings__MySql: server=userservice_db;port=3306;database=users;uid=${USER_SQL_USERNAME};pwd=${USER_SQL_PASSWORD};

  userservice_db:
    image: mysql:latest
    container_name: 'StarboardSocial-UserService-DB'
    restart: unless-stopped
    networks:
      - user_starboardsocial_net
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_SQL_PASSWORD}
      MYSQL_USER: ${USER_SQL_USERNAME}
      MYSQL_PASSWORD: ${USER_SQL_PASSWORD}
      MYSQL_DATABASE: users
    volumes:
      - starboardsocial_user_db_data:/var/lib/mysql
        
volumes:
  starboardsocial_user_db_data:
    name: starboardsocial_user_db_data
    
networks:
  starboardsocial_net:
    name: starboardsocial_net
    driver: bridge
  user_starboardsocial_net:
    name: user_starboardsocial_net
    driver: bridge