name: Deploy to IRA server

on:
  workflow_call:
    
jobs:
  deploy:
    name: Deploy to IRA server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          envkey_RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          envkey_USER_SQL_USERNAME: ${{ secrets.USER_SQL_USERNAME }}
          envkey_USER_SQL_PASSWORD: ${{ secrets.USER_SQL_PASSWORD }}
          directory: ./
          file_name: .env
          fail_on_empty: false
          sort_keys: false
          
      - name: Copy docker-compose.yml to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./docker-compose.yml
          remote: /home/starboard/userservice/docker-compose.yml
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          
      - name: Copy .env file to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./.env
          remote: /home/starboard/userservice/.env
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          
      - name: SSH to IRA and deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/starboard &&
            mkdir -p userservice &&
            cd userservice &&
            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ vars.REGISTRY_URL }} &&
            docker pull ${{ vars.REGISTRY_URL }}/userservice:prod &&
            docker compose up -d &&
            rm .env
