name: Push-Dev-Workflow

on:
  push:
    branches:
      - development

jobs:
  sonarqube:
    secrets: inherit
    uses: ./.github/workflows/sonarqube-workflow.yaml
    
  build_upload_image:
    secrets: inherit
    uses: ./.github/workflows/upload-to-registry.yaml