name: Push image to registry

on:
  workflow_call: 


jobs:
  build_upload_image:
    name: Build image and upload to registry
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push prod image
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.REGISTRY_URL }}/userservice:prod
          
      - name: Build and push dev image
        if: ${{ github.ref_name == 'development' }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.REGISTRY_URL }}/userservice:dev